## Numpy


NumPy is a fundamental library for scientific computing in python . it provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. 

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

## Creating array using numpy
## create a 1D array

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [7]:
## reshape
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [ ]:
# 1D Array
arr3 = np.array([[1,2,3,4,5]])
arr3.shape

(1, 5)

In [11]:
## 2D Array
arr4 = np.array([[1,2,3,4,5],[3,4,5,6,7]])
print(arr4)
print(arr4.shape)

[[1 2 3 4 5]
 [3 4 5 6 7]]
(2, 5)


In [14]:
## USe of arrangr=e and reshape function
# here the index of arange is first is starting number , second is ending number and last is gap between the number 
np.arange(0,10,1).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [15]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
## Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
## Attributes of numpy
arr = np.array([[1,2,3],[4,5,6]])

print("Array:\n",arr)
print("shape:",arr.shape)
print("Number of Dimensions:",arr.ndim)
print("Size(number of elements): ",arr.size)
print("Data Type:",arr.dtype)
print("Item size (in bytes):",arr.itemsize) 

Array:
 [[1 2 3]
 [4 5 6]]
shape: (2, 3)
Number of Dimensions: 2
Size(number of elements):  6
Data Type: int64
Item size (in bytes): 8


In [ ]:
## Numpy Vectorized Operation

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([3,4,5,6,7])

## Element wise Addition

print("Addition:",arr1+arr2)

## ElementWise Subtraction
print("Subtraction: ",arr1-arr2)

## ElementWise Multiplication
print("Multiplication: ",arr1*arr2)

## ElementWise Division
print("Division: ", arr1/arr2)



Addition: [ 4  6  8 10 12]
Subtraction:  [-2 -2 -2 -2 -2]
Multiplication:  [ 3  8 15 24 35]
Division:  [0.33333333 0.5        0.6        0.66666667 0.71428571]


In [26]:
## Universal Function
arr = np.array([2,3,4,5,6])

## square Root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## Sine
print(np.sin(arr))

# natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [29]:
## Array  Slicing operation and Indexing operation

arr = np.array([[1,2,3,4,5],[5,6,7,8,9],[3,4,5,6,7]])
print("Array: \n",arr)

Array: 
 [[1 2 3 4 5]
 [5 6 7 8 9]
 [3 4 5 6 7]]


In [31]:
print(arr[0][0])

1


In [42]:
arr[0:2,2:]

array([[3, 4, 5],
       [7, 8, 9]])

In [32]:
arr[1][1]

np.int64(6)

In [34]:
arr[1:]

array([[5, 6, 7, 8, 9],
       [3, 4, 5, 6, 7]])

In [35]:
arr[0:]

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9],
       [3, 4, 5, 6, 7]])

In [36]:
arr[:2]

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9]])

In [38]:
arr[1:2]

array([[5, 6, 7, 8, 9]])

In [39]:
arr[1:,2:]

array([[7, 8, 9],
       [5, 6, 7]])

In [43]:
## Modification in Array

arr[0,0] = 110
print(arr)


[[110   2   3   4   5]
 [  5   6   7   8   9]
 [  3   4   5   6   7]]


In [44]:
arr[1:,:3]=50
print(arr)

[[110   2   3   4   5]
 [ 50  50  50   8   9]
 [ 50  50  50   6   7]]


In [45]:
### statistics concepts -- Normalization
## to have a mean of 0 and standard deviation of 1
data = np.array([1,2,3,4,5])

# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean)/std_dev
print("Normalized Data: ", normalized_data)

Normalized Data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [46]:
## Mean
mean = np.mean(data)

# Median
median = np.median(data)

# Standard Deviation
std_dev = np.std(data)
print("Standard Deviation: ",std_dev)

## Varience
varience = np.var(data)

Standard Deviation:  1.4142135623730951


In [47]:
## Logical Operation
data = np.array([1,2,3,4,5,5,6,7,8,9])

print(data[data>5])
data>4


[6 7 8 9]


array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [48]:
data[(data>=5) & (data<8)]

array([5, 5, 6, 7])